models/appointment.py
from utils.db import db

class Appointment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(20))  
    date = db.Column(db.Date)  
    hour = db.Column(db.Time) 
    service = db.Column(db.String(100))

    def __init__(self, fullname, email, phone, date, hour, service):
        self.fullname = fullname
        self.email = email
        self.phone = phone
        self.date = date
        self.hour = hour
        self.service = service

app.py
from flask import Flask
from routes.appointments import appointments
from utils.db import db

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = "mysql://root:123456@localhost/appointmentsdb"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)

app.register_blueprint(appointments)

routes/appointments.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.appointment import Appointment
from utils.db import db

appointments = Blueprint("appointments", __name__)


@appointments.route("/")
def home():
    appointments = Appointment.query.all()
    return render_template("index.html", appointments=appointments)


@appointments.route("/book", methods=["POST"])
def add_appointment():
    fullname = request.form["fullname"]
    email = request.form["email"]
    phone = request.form["phone"]
    date = request.form["date"]
    hour = request.form["hour"]
    service = request.form["service"]

    new_appointment = Appointment(fullname, email, phone, date, hour, service)
    db.session.add(new_appointment)
    db.session.commit()

    return redirect(url_for("appointments.home"))


@appointments.route("/update/<id>", methods=["POST", "GET"])
def update_appointment(id):
    appointment = Appointment.query.get(id)

    if request.method == "POST":
        appointment.fullname = request.form["fullname"]
        appointment.email = request.form["email"]
        appointment.phone = request.form["phone"]
        appointment.date = request.form["date"]
        appointment.hour = request.form["hour"]
        appointment.service = request.form["service"]
        db.session.commit()
        return redirect(url_for("appointments.adminAppointments"))
    return render_template("update.html", appointment=appointment)


@appointments.route("/delete/<id>")
def delete_appointment(id):
    appointment = Appointment.query.get(id)
    db.session.delete(appointment)
    db.session.commit()
    return redirect(url_for("appointments.home"))


@appointments.route("/comments")
def comments():
    return render_template("comments.html")


@appointments.route("/adminAppointments")
def adminAppointments():
    appointments = Appointment.query.all()
    return render_template("adminAppointments.html", appointments=appointments)

templates/adminAppointments.html
{% extends 'layout.html' %}

{% block body %}
<section class="gradient-custom">
    <div class="container my-5 py-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10 col-xl-8">
                <div class="card shadow-sm">
                <div class="card-body p-4">
                    <h4 class="text-center mb-4 pb-2">Administrar citas</h4>
                        {% for appointment in appointments %}
                        <div class="card mb-3 border-left-primary"> 
                            <div class="card-header">
                                <p class="h3">{{appointment.fullname}}</p>
                            </div>
                            <div class="card-body">
                                <div class="card-title">
                                    <h5 class="mb-1"><span class="light-text">Fecha:</span> {{appointment.date}}</h5>
                                    <h5 class="mb-1"><span class="light-text">Hora:</span> {{appointment.hour}}</h5>
                                    <h5 class="mb-1"><span class="light-text">Servicio:</span> {{appointment.service}}</h5>
                                </div>
                                <div class="card-text">
                                    <h5 class="mb-1"><span class="light-text">Email:</span> {{appointment.email}}</h5>
                                    <h5><span class="light-text">Teléfono:</span> {{appointment.phone}}</h5>
                                </div>                                                              
                                <div class="mt-4">
                                    <a href="{{ url_for('appointments.update_appointment', id=appointment.id)}}" class="btn btn-primary btn-sm">Actualizar</a>
                                    <a href="{{ url_for('appointments.delete_appointment', id=appointment.id)}}" class="btn btn-danger btn-sm">Eliminar</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/comments.html
{% extends 'layout.html' %}


{% block body %}

<section class="gradient-custom">
    <div class="container my-5 py-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10 col-xl-8">
                <div class="card">
                <div class="card-body p-4">
                    <h4 class="text-center mb-4 pb-2"></h4>
                    <div class="row">
                        <div class="col">
                            <div class="d-flex flex-start">
                                <img class="rounded-circle shadow-1-strong me-3"
                                src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/The_Rock_2023.jpg/250px-The_Rock_2023.jpg" alt="avatar" width="65"
                                height="65" />
                                <div class="flex-grow-1 flex-shrink-1">
                                    <div>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <p class="mb-1">
                                                Dwayne Johnson <span class="small">- 2 hours ago</span>
                                            </p>
                                            <a href="#!"><i class="fas fa-reply fa-xs"></i><span class="small"> reply</span></a>
                                        </div>
                                        <p class="small mb-0">
                                            Excelente servicio, muy amables y con mucha actitud para hacer su trabajo.
                                        </p>
                                    </div>
                                    <div class="d-flex flex-start mt-4">
                                        <a class="me-3" href="#">
                                            <img class="rounded-circle shadow-1-strong"
                                            src="https://imgs.search.brave.com/9P6mSOjrKeDaUX_AofLmGIBqgUqpoioxQkCRrOSYjIo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMubXViaWNkbi5u/ZXQvaW1hZ2VzL2Nh/c3RfbWVtYmVyLzI0/MzI5L2NhY2hlLTIy/MTgtMTYwMjc1MDgx/OC9pbWFnZS13ODU2/LmpwZz9zaXplPTgw/MHg" alt="avatar"
                                            width="65" height="65" />
                                        </a>
                                        <div class="flex-grow-1 flex-shrink-1">
                                            <div>
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <p class="mb-1">
                                                        RobertoCullen <span class="small">- 3 days ago</span>
                                                    </p>
                                                </div>
                                                <p class="small mb-0">
                                                    Me gusto mucho que fue muy facil sacar una cita en su pagina y que aparte me hayan atendido muy bien, es la segunda vez que voy aqui
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-start mt-4">
                                            <a class="me-3" href="#">
                                                <img class="rounded-circle shadow-1-strong"
                                                src="https://th.bing.com/th/id/OIP.nwZb53PdBZozQ1EZ-r6_LwHaGq?rs=1&pid=ImgDetMain" alt="avatar"
                                                width="65" height="65" />
                                            </a>
                                        <div class="flex-grow-1 flex-shrink-1">
                                            <div>
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <p class="mb-1">
                                                        TaylorWolf<span class="small">- 4 hours ago</span>
                                                    </p>
                                                </div>
                                                <p class="small mb-0">
                                                    A mi tambien me gusto mucho que se puede sacar unas cita mu facilmente
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex flex-start mt-4">
                                <img class="rounded-circle shadow-1-strong me-3"
                                src="https://imgs.search.brave.com/KjJoNtWX-Oz5ue8893csJDw1PsvxC-AWPgJ34hsMjt0/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9paDEu/cmVkYnViYmxlLm5l/dC9pbWFnZS40ODQ0/OTE3NTkzLjUyMDQv/cmFmLDM2MHgzNjAs/MDc1LHQsZmFmYWZh/OmNhNDQzZjQ3ODYu/anBn" alt="avatar" width="65"
                                height="65" />
                                <div class="flex-grow-1 flex-shrink-1">
                                    <div>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <p class="mb-1">
                                                Pedro Nuñes <span class="small">- five days ago</span>
                                            </p>
                                            <a href="#!"><i class="fas fa-reply fa-xs"></i><span class="small"> reply</span></a>
                                        </div>
                                        <p class="small mb-0">
                                            Me encanta la atencion en la partye de la barba y el bigote super recomiendo sacar cita lo  antes posible.
                                        </p>
                                    </div>

                      <div class="d-flex flex-start mt-4">
                        <a class="me-3" href="#">
                          <img class="rounded-circle shadow-1-strong"
                            src="https://imgs.search.brave.com/1OK_zSmTfl1DEO3l6h2kXrjxzMWH7rYzzjsTxJ39_PY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMubXViaWNkbi5u/ZXQvaW1hZ2VzL2Nh/c3RfbWVtYmVyLzI1/NTIvY2FjaGUtMjA3/LTE1MjQ5MjI4NTAv/aW1hZ2Utdzg1Ni5q/cGc_c2l6ZT04MDB4"
                            width="65" height="65" />
                        </a>
                        <div class="flex-grow-1 flex-shrink-1">
                          <div>
                            <div class="d-flex justify-content-between align-items-center">
                              <p class="mb-1">
                                Brad Perez <span class="small">- 4 hours ago</span>
                              </p>
                            </div>
                            <p class="small mb-0">
Estoy muy deacuero Pedro a mi tambien me dejaron la barba muy perfilada a parte que es muy facil sacr unaz cita solo  no toma mas de 5 minutos.
                            </p>
                          </div>
                        </div>
                      </div>

                      <div class="d-flex flex-start mt-4">
                        <a class="me-3" href="#">
                          <img class="rounded-circle shadow-1-strong"
                            src="https://imgs.search.brave.com/34LX2Yi2JbY2VSMhz7oOSFXN95dchgd_wIYGMgEdYc0/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLmRh/aWx5bWFpbC5jby51/ay9pL3BpeC8yMDE3/LzA4LzA2LzE5LzQz/MDY5NkRGMDAwMDA1/NzgtMC1pbWFnZS1t/LTQ2XzE1MDIwNDMz/NjQ0MDAuanBn"
                            width="65" height="65" />
                        </a>
                        <div class="flex-grow-1 flex-shrink-1">
                          <div>
                            <div class="d-flex justify-content-between align-items-center">
                              <p class="mb-1">
                                Tomas Hernández <span class="small">- 5 hours ago</span>
                              </p>
                            </div>
                            <p class="small mb-0">
Ame el portal de la barberia al igual que me gusto mi corte de cabello
                            </p>
                          </div>
                        </div>
                      </div>

                      <div class="d-flex flex-start mt-4">
                        <a class="me-3" href="#">
                          <img class="rounded-circle shadow-1-strong"
                            src="https://imgs.search.brave.com/n0Zg1yXsU-Hy2u9Ll0pXoYDEPANzkU-me2-SHT499zM/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/YWNlc2hvd2Jpei5j/b20vaW1hZ2VzL3Bo/b3RvL3RvbV9oaWRk/bGVzdG9uLmpwZw" alt="avatar"
                            width="65" height="65" />
                        </a>
                        <div class="flex-grow-1 flex-shrink-1">
                          <div>
                            <div class="d-flex justify-content-between align-items-center">
                              <p class="mb-1">
                                Tomas Herrera <span class="small">- 6 hours ago</span>
                              </p>
                            </div>
                            <p class="small mb-0">
Yo voy desde hace años y la facibilidad de reserva es por lo  que me gusta the barber place.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block body %}
    <div class="page-container">
        <div class="barber-pole left">
            <div class="anim-element"></div>
        </div>
        
        <div class="barber-pole right">
            <div class="anim-element"></div>
        </div>
    </div>

    <div class="container formulario fromularioContenido">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel"> 
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" class="active"></li>
                <li data-target="#carouselExampleIndicators" ></li>
                <li data-target="#carouselExampleIndicators" ></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block mx-auto" src="{{url_for('static', filename='media/flip.png')}}" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block mx-auto" src="{{url_for('static', filename='media/dos.png')}}" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block mx-auto" src="{{url_for('static', filename='media/car2.png')}}" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev"> 
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next"> 
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    
    <section class="gradient-custom">
        <div class="container my-5 py-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 col-lg-10 col-xl-8">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="container">
                                <div class="row d-flex justify-content-center">
                                    <div class="col">
                                        <div class="jumbotron jumbotron-fluid">
                                            <div class="container formularioContenido">
                                                <h1 class="display-4">¡Agenda tu cita!</h1>
                                                <p class="lead">Contamos con los mejores especialistas.</p>
                                            </div>
                                        </div>
                                        <form action="/book" method="POST">
                                            <div class="form-group formularioContenido">
                                                <label for="fullname">Ingrese Nombre</label>
                                                <input type="text" class="form-control" id="fullname" name="fullname" placeholder="Nombre Completo"/>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6 form-group formularioContenido">
                                                    <label for="email">Ingrese Email</label>
                                                    <input type="email" class="form-control" id="email" name="email" placeholder="Email"/>
                                                </div>
                                                <div class="col-md-6 form-group formularioContenido">
                                                    <label for="phone">Ingrese Teléfono</label>
                                                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Teléfono"/>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6 form-group formularioContenido">
                                                    <label for="date">Seleccione la fecha para su cita:</label>
                                                    <input type="date" id="date" name="date" class="form-control" required/>
                                                </div>
                                                <div class="col-md-6 form-group formularioContenido">
                                                    <label for="hour">Horario:</label>
                                                    <input type="time" id="hour" name="hour" class="form-control" required>
                                                </div>
                                            </div>
                                            <div class="form-group formularioContenido">
                                                <label for="service">Motivo de cita:</label>
                                                <select id="service" name="service" required class="form-control">
                                                    <option value="">--Seleccione un servicio--</option>
                                                    <option value="corte">Corte de pelo</option>
                                                    <option value="afeitado">Afeitado</option>
                                                    <option value="barba">Recorte de barba</option>
                                                </select>
                                            </div>
                                            <div class="form-group formularioContenido">
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox" id="gridCheck">
                                                    <label class="form-check-label" for="gridCheck">
                                                        <a href="javascript:void(0)" onclick="showTerms()">Acepto los términos y condiciones</a>
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="form-group text-center formularioContenido">
                                                <button type="submit" class="btn btn-primary" id="submitBtn" disabled>Agendar Cita</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    




    
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link href="{{url_for('static', filename='css/styles.css')}}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <title>Barbería Pilares</title>
    </head>
<body>
    <div class="header">
        <nav class="navbar navbar-expand-lg justify-content-center">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="{{url_for('static', filename='media/logog.png')}}" width="20%" alt="Logo" class="d-inline-block align-top">
                </a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/comments">Reseñas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/adminAppointments">Citas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
    </div>
    {% block body %}
    {% endblock %}
    <footer class="bg-dark text-white pt-5 pb-4">
        <div class="container text-center text-md-left">
            <div class="row text-center text-md-left">
                <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">¿Cuál es nuestra misión?</h5>
                    <p>Proporcionar una plataforma intuitiva y confiable que facilite la reserva de citas para servicios de barbería, mejorando la experiencia tanto para los clientes como para los profesionales.</p>
                </div>
                <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">¿Cuál es nuestra visión?</h5>
                    <p>Ser el puente digital líder que conecta a individuos con los mejores profesionales de barbería, estableciendo un nuevo estándar global en la accesibilidad y gestión de cuidado personal.</p>
                </div>
                <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Contáctanos</h5>
                    <p>
                        <i class="fas fa-envelope mr-3"></i> thebarberplace@gmail.com
                    </p>
                    <p>
                        <i class="fas fa-phone mr-3"></i> Whatsapp: 55-18-06-97-45
                    </p>
                    <p>
                        <i class="fab fa-facebook mr-3"></i> Facebook: The Barber Place
                    </p>
                    <p>
                        <i class="fab fa-instagram mr-3"></i> Instagram: thebarberplace
                    </p>
                </div>
            </div>
            <hr class="mb-4">
            <div class="row align-items-center">
                <div class="col-md-7 col-lg-8">
                    <p>&copy; 2024 The Barber Place | Todos los derechos reservados</p>
                </div>
            </div>
        </div>
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{url_for('static', filename='scripts/script.js')}}"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

</body>
</html>

templates/update.html
{% extends 'layout.html' %}

{% block body %}
<section class="gradient-custom">
    <div class="container my-5 py-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10 col-xl-8">
                <div class="card shadow-sm">
                    <div class="card-body p-4">
                        <h4 class="text-center mb-4 pb-2">Actualizar Cita</h4>
                        <form action="/update/{{appointment.id}}" method="POST">
                            <div class="form-group mb-3">
                                <input type="text" class="form-control" name="fullname" placeholder="Actualice Nombre" value="{{appointment.fullname}}"/>
                            </div>
                            <div class="form-group mb-3">
                                <input type="text" class="form-control" name="email" placeholder="Actualice Email" value="{{appointment.email}}"/>
                            </div>
                            <div class="form-group mb-3">
                                <input type="text" class="form-control" name="phone" placeholder="Actualice Teléfono" value="{{appointment.phone}}"/>
                            </div>
                            <div class="form-group mb-3">
                                <input type="date" class="form-control" name="date" placeholder="Seleccione la fecha" value="{{appointment.date}}"/>
                            </div>
                            <div class="form-group mb-3">
                                <input type="time" class="form-control" name="hour" placeholder="Seleccione la hora" value="{{appointment.hour}}"/>
                            </div>
                            <div class="form-group mb-3">
                                <select name="service" class="form-control">
                                    <option value="corte" {% if appointment.service == 'corte' %} selected {% endif %}>Corte de pelo</option>
                                    <option value="afeitado" {% if appointment.service == 'afeitado' %} selected {% endif %}>Afeitado</option>
                                    <option value="barba" {% if appointment.service == 'barba' %} selected {% endif %}>Recorte de barba</option>
                                </select>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary" id="actualizarCita">Actualizar Cita</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}